
#url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wechatproject?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
  redis:
    port: 6379
    password: root
  jpa:
    show-sql: true
wx:
  appId: wx5fb04558f8fa71ce
  appSecret: 7e178973a07809c9156e17625aec07cf
  grantType: authorization_code
  MCH_ID: 1518998751
  appkey: WKD3910pklz93ms8NXU0Mmlaeowv95B2
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: basePackage.entity
logging:
  level:
    basePackage.dao : debug
 
