
#url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wechatproject?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
  redis:
    port: 6379
    password: root
  jpa:
    show-sql: true
wx:
  appId: wx8c17b99b642d478e
  appSecret: 47b9a631bfa10b1e24fa0e0a07693a1e
  grantType: authorization_code
  MCH_ID: 'aewaeaew'
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: basePackage.entity
logging:
  level:
    basePackage.dao : debug
 
